# Generated by Django 4.1.3 on 2022-12-01 01:23

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses ={
        "to do": "A task that has not yet been started",
        "in progress": "A task that has already been worked on",
        "done": "A task that has been marked complete"
    }

    Status = apps.get_model("issues","Status")
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

def populate_priority(apps, schemaeditor):
    priorities = {
        "low": "a low priority issue",
        "medium": "a medium priority issue",
        "High": "a high priority"
    }

    Priority = apps.get_model("issues", "Priority")
    for key, value in priorities.items():
        pr_obj = Priority(name=key, description=value)
        pr_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]
